### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by hubb2** [jasperproject/jasperproject.github.io#40]
"ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 143, in <module>
    app = Jasper()
  File "./jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 34, in get_instance
    config = cls.get_config()
  File "/home/pi/jasper/client/stt.py", line 235, in get_config
    if 'hmmdefs' in profile['julius']:
TypeError: argument of type 'NoneType' is not iterable"

This is the error im getting when running jasper through jasper.py 
and if I run it through main.py a similar error occurs. 
Can anyone help me please?

**Comment by Kirlocca** [comment]
Can confirm the exact same error with the latest release

```
ERROR:root:Error occured!
Traceback (most recent call last):
File "./jasper.py", line 146, in <module>
app = Jasper()
File "./jasper.py", line 109, in __init__
stt_passive_engine_class.get_passive_instance(),
File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
return cls.get_instance('keyword', phrases)
File "/home/pi/jasper/client/stt.py", line 34, in get_instance
config = cls.get_config()
File "/home/pi/jasper/client/stt.py", line 235, in get_config
if 'hmmdefs' in profile['julius']:
TypeError: argument of type 'NoneType' is not iterable
```

Are there any solutions yet?
