### ISSUE TITLE
Issues starting Jasper

### ISSUE THREAD

**Issue by talithathompson** [jasperproject/jasperproject.github.io#62]
Please do help me as i am a newbee

After configuring Jasper, tried starting Jasper by
/home/pi/jasper/jasper.py

but ended up with error (see below)
```
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/kidde-ubuntu/pi/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/home/kidde-ubuntu/pi/jasper/jasper.py", line 77, in __init__
    self.config = yaml.safe_load(f)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "/home/kidde-ubuntu/.jasper/profile.yml", line 1, column 1
expected <block end>, but found '<scalar>'
  in "/home/kidde-ubuntu/.jasper/profile.yml", line 11, column 11
```

What should I do?

Thank you all for you support in advance

**Comment by Holzhaus** [comment]
Your Config file is invalid. I assume you have accidently used a backtick `` ` `` or something like that instead of normal quote `'`.
