### ISSUE TITLE
having issues in compiling  jasper.py

### ISSUE THREAD

**Issue by ezargar** [jasperproject/jasperproject.github.io#85]
pi@raspberrypi:~/g014b2b $ /home/pi/jasper/jasper.py 
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/pi/phonetisaurus/g014b2b.fst --input=/tmp/tmpKHonAt.g2p --words --isfile' return with exit status -11
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 321, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/pi/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/pi/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/pi/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed

**Comment by pudility** [comment]
Same here - I would love to find a fix.

**Comment by pudility** [comment]
After testing it a little more, I was able to get `phonetisaurus` installed and "working" (sort-of) by using [this repository](https://github.com/AdolfVonKleist/Phonetisaurus). Unfortunately it did not understand me at all so I switched to witai which has been working pretty well.

**Comment by ezargar** [comment]
thank you but i installed google engine...i'm pretty good with it
